mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml    #扫描xml文件位置
  global-config:
    db-config:
      table-underline: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    schema: classpath:db/schema-h2.sql
    #    data: classpath:db/data-h2.sql
    url: jdbc:mysql://192.168.1.123:3306/law
    username: root
    password: 123456
server:
  port: 8089
debug: true
