mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml    #扫描xml文件位置
  global-config:
    db-config:
      table-underline: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    schema: classpath:db/schema-h2.sql
    #    data: classpath:db/data-h2.sql
    url: jdbc:mysql://218.2.26.18:9192/law
    username: law_user
    password: lv350166
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8 #时区问题
server:
  port: 8089
debug: false
